version: '3'

services:
  ##### POSTGRES #################################
  db:
    image: postgres:14
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  telegram_bot:
    build: .
    restart: always
    env_file:
      - .env.prod
    entrypoint: [ "/docker-entrypoint.sh", "apps/telegram_bot/main.py" ]
    depends_on:
      db:
        condition: service_healthy

  notifier:
    build: .
    restart: always
    env_file:
      - .env.prod
    entrypoint: [ "/docker-entrypoint.sh", "apps/notifications/main.py" ]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
